name: Calculator

on:
  push:
    branches: [main]

jobs:

  somar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar pytest
        run: pip install pytest

      - name: Testar soma
        run: pytest Calculator_python/test_soma.py -k test_somar


  subtrair:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar pytest
        run: pip install pytest

      - name: Testar subtração
        run: pytest Calculator_python/test_subtrair.py -k test_subtrair


  multiplicar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar pytest
        run: pip install pytest

      - name: Testar multiplicação
        run: pytest Calculator_python/test_multiplicar.py -k test_multiplicar


  dividir:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar pytest
        run: pip install pytest

      - name: Testar divisão
        run: pytest Calculator_python/test_dividir.py -k test_dividir